Bump to Build 3095 Chop Shop DLC
Bob74/bob74_ipl pull request #130
Opened 2024-01-08 13:07 UTC by ItzCelyrian

Added LICENSE.md (Non-Commerical 4.0)
Added 3095 - Chop Shop DLC
Added 2189 - Cayo Perico DLC
Fixed routing on Cayo Perico (Waypoints work if the player is on the island)
Fixed Minimap of Cayo Perico

TODO:
- In my servers case this wasn't necessairy but currently on Version: "3.0a" the loading of 2189 and 3095 is permanently enabled, this will need to be added to client.lua in order to allow disabling of elements.

2024-01-08 13:11 UTC, ItzCelyrian commented
In this PR the following files should be updated and or ignored/adjusted.

Since I will be forking this into my own Loader I just wanted to contribute the changes I made up to 3095.

The changes which you might want to revert are found within:
- README.md (Since linkage works to my repository on my branch.)
- fxmanifest.lua (I added myself to the Authors inside my repository, you can remove this from the PR by cherry picking.)
- LICENSE.md can be scrapped, if you wish to do so.

2024-01-11 21:09 UTC, QuirkyCarlos approved these changes

2024-01-11 21:17 UTC, QuirkyCarlos approved these changes
Tested myself on my dev server literally can just drag into bob_ipl folder fine

2024-01-12 22:53 UTC, Virus18sp commented
Will you add support for 2944 too? there are some good interiors.

2024-01-14 20:16 UTC, ItzCelyrian commented
@Virus18sp I will create a new Version on my fork, continue tests with 2944 and then if it goes well add them to the Pull Request.👍

2024-01-15 19:53 UTC, ItzCelyrian commented
- Added San ANdreas Mercenary (2944)
- Added Summer Special (- [Arcade])

2024-02-23 08:28 UTC, Sina30 commented
You shouldn't use it yet because it only causes problems at the casinos, and it also only causes problems near the harbor

2024-03-15 07:17 UTC, ItzCelyrian commented on README.md
I made the Readme redirect to my Repo. That is why I recommended a Cherry-Pick merge.

2024-03-31 17:49 UTC, TheIndra55 requested changes
I'm sorry but this does not follow the code structure of this project at all. I'll reimplement these changes myself in another PR.

2024-04-05 22:32 UTC, TheIndra55 commented
Closing this since the latest DLCs have been added in #133.

There's still some stuff missing like arcades and cayo, but don't be hesitant to open a pull request for those. Please do follow the existing code.

2024-04-05 22:32 UTC, closed without merging